
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ValidationCode` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ValidationCode
 * 
 */
export type ValidationCodeModel = runtime.Types.Result.DefaultSelection<Prisma.$ValidationCodePayload>

export type AggregateValidationCode = {
  _count: ValidationCodeCountAggregateOutputType | null
  _avg: ValidationCodeAvgAggregateOutputType | null
  _sum: ValidationCodeSumAggregateOutputType | null
  _min: ValidationCodeMinAggregateOutputType | null
  _max: ValidationCodeMaxAggregateOutputType | null
}

export type ValidationCodeAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  type: number | null
}

export type ValidationCodeSumAggregateOutputType = {
  id: number | null
  userId: number | null
  type: number | null
}

export type ValidationCodeMinAggregateOutputType = {
  id: number | null
  userId: number | null
  code: string | null
  createdAt: Date | null
  updatedAt: Date | null
  expiredAt: Date | null
  used: boolean | null
  type: number | null
}

export type ValidationCodeMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  code: string | null
  createdAt: Date | null
  updatedAt: Date | null
  expiredAt: Date | null
  used: boolean | null
  type: number | null
}

export type ValidationCodeCountAggregateOutputType = {
  id: number
  userId: number
  code: number
  createdAt: number
  updatedAt: number
  expiredAt: number
  used: number
  type: number
  _all: number
}


export type ValidationCodeAvgAggregateInputType = {
  id?: true
  userId?: true
  type?: true
}

export type ValidationCodeSumAggregateInputType = {
  id?: true
  userId?: true
  type?: true
}

export type ValidationCodeMinAggregateInputType = {
  id?: true
  userId?: true
  code?: true
  createdAt?: true
  updatedAt?: true
  expiredAt?: true
  used?: true
  type?: true
}

export type ValidationCodeMaxAggregateInputType = {
  id?: true
  userId?: true
  code?: true
  createdAt?: true
  updatedAt?: true
  expiredAt?: true
  used?: true
  type?: true
}

export type ValidationCodeCountAggregateInputType = {
  id?: true
  userId?: true
  code?: true
  createdAt?: true
  updatedAt?: true
  expiredAt?: true
  used?: true
  type?: true
  _all?: true
}

export type ValidationCodeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ValidationCode to aggregate.
   */
  where?: Prisma.ValidationCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationCodes to fetch.
   */
  orderBy?: Prisma.ValidationCodeOrderByWithRelationInput | Prisma.ValidationCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ValidationCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ValidationCodes
  **/
  _count?: true | ValidationCodeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ValidationCodeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ValidationCodeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ValidationCodeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ValidationCodeMaxAggregateInputType
}

export type GetValidationCodeAggregateType<T extends ValidationCodeAggregateArgs> = {
      [P in keyof T & keyof AggregateValidationCode]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateValidationCode[P]>
    : Prisma.GetScalarType<T[P], AggregateValidationCode[P]>
}




export type ValidationCodeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ValidationCodeWhereInput
  orderBy?: Prisma.ValidationCodeOrderByWithAggregationInput | Prisma.ValidationCodeOrderByWithAggregationInput[]
  by: Prisma.ValidationCodeScalarFieldEnum[] | Prisma.ValidationCodeScalarFieldEnum
  having?: Prisma.ValidationCodeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ValidationCodeCountAggregateInputType | true
  _avg?: ValidationCodeAvgAggregateInputType
  _sum?: ValidationCodeSumAggregateInputType
  _min?: ValidationCodeMinAggregateInputType
  _max?: ValidationCodeMaxAggregateInputType
}

export type ValidationCodeGroupByOutputType = {
  id: number
  userId: number
  code: string
  createdAt: Date
  updatedAt: Date
  expiredAt: Date
  used: boolean
  type: number
  _count: ValidationCodeCountAggregateOutputType | null
  _avg: ValidationCodeAvgAggregateOutputType | null
  _sum: ValidationCodeSumAggregateOutputType | null
  _min: ValidationCodeMinAggregateOutputType | null
  _max: ValidationCodeMaxAggregateOutputType | null
}

type GetValidationCodeGroupByPayload<T extends ValidationCodeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ValidationCodeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ValidationCodeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ValidationCodeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ValidationCodeGroupByOutputType[P]>
      }
    >
  >



export type ValidationCodeWhereInput = {
  AND?: Prisma.ValidationCodeWhereInput | Prisma.ValidationCodeWhereInput[]
  OR?: Prisma.ValidationCodeWhereInput[]
  NOT?: Prisma.ValidationCodeWhereInput | Prisma.ValidationCodeWhereInput[]
  id?: Prisma.IntFilter<"ValidationCode"> | number
  userId?: Prisma.IntFilter<"ValidationCode"> | number
  code?: Prisma.StringFilter<"ValidationCode"> | string
  createdAt?: Prisma.DateTimeFilter<"ValidationCode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ValidationCode"> | Date | string
  expiredAt?: Prisma.DateTimeFilter<"ValidationCode"> | Date | string
  used?: Prisma.BoolFilter<"ValidationCode"> | boolean
  type?: Prisma.IntFilter<"ValidationCode"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ValidationCodeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  used?: Prisma.SortOrder
  type?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  _relevance?: Prisma.ValidationCodeOrderByRelevanceInput
}

export type ValidationCodeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ValidationCodeWhereInput | Prisma.ValidationCodeWhereInput[]
  OR?: Prisma.ValidationCodeWhereInput[]
  NOT?: Prisma.ValidationCodeWhereInput | Prisma.ValidationCodeWhereInput[]
  userId?: Prisma.IntFilter<"ValidationCode"> | number
  code?: Prisma.StringFilter<"ValidationCode"> | string
  createdAt?: Prisma.DateTimeFilter<"ValidationCode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ValidationCode"> | Date | string
  expiredAt?: Prisma.DateTimeFilter<"ValidationCode"> | Date | string
  used?: Prisma.BoolFilter<"ValidationCode"> | boolean
  type?: Prisma.IntFilter<"ValidationCode"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type ValidationCodeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  used?: Prisma.SortOrder
  type?: Prisma.SortOrder
  _count?: Prisma.ValidationCodeCountOrderByAggregateInput
  _avg?: Prisma.ValidationCodeAvgOrderByAggregateInput
  _max?: Prisma.ValidationCodeMaxOrderByAggregateInput
  _min?: Prisma.ValidationCodeMinOrderByAggregateInput
  _sum?: Prisma.ValidationCodeSumOrderByAggregateInput
}

export type ValidationCodeScalarWhereWithAggregatesInput = {
  AND?: Prisma.ValidationCodeScalarWhereWithAggregatesInput | Prisma.ValidationCodeScalarWhereWithAggregatesInput[]
  OR?: Prisma.ValidationCodeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ValidationCodeScalarWhereWithAggregatesInput | Prisma.ValidationCodeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ValidationCode"> | number
  userId?: Prisma.IntWithAggregatesFilter<"ValidationCode"> | number
  code?: Prisma.StringWithAggregatesFilter<"ValidationCode"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ValidationCode"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ValidationCode"> | Date | string
  expiredAt?: Prisma.DateTimeWithAggregatesFilter<"ValidationCode"> | Date | string
  used?: Prisma.BoolWithAggregatesFilter<"ValidationCode"> | boolean
  type?: Prisma.IntWithAggregatesFilter<"ValidationCode"> | number
}

export type ValidationCodeCreateInput = {
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  expiredAt: Date | string
  used?: boolean
  type?: number
  user: Prisma.UserCreateNestedOneWithoutValidationCodeInput
}

export type ValidationCodeUncheckedCreateInput = {
  id?: number
  userId: number
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  expiredAt: Date | string
  used?: boolean
  type?: number
}

export type ValidationCodeUpdateInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutValidationCodeNestedInput
}

export type ValidationCodeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ValidationCodeCreateManyInput = {
  id?: number
  userId: number
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  expiredAt: Date | string
  used?: boolean
  type?: number
}

export type ValidationCodeUpdateManyMutationInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ValidationCodeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ValidationCodeListRelationFilter = {
  every?: Prisma.ValidationCodeWhereInput
  some?: Prisma.ValidationCodeWhereInput
  none?: Prisma.ValidationCodeWhereInput
}

export type ValidationCodeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ValidationCodeOrderByRelevanceInput = {
  fields: Prisma.ValidationCodeOrderByRelevanceFieldEnum | Prisma.ValidationCodeOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ValidationCodeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  used?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type ValidationCodeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type ValidationCodeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  used?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type ValidationCodeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiredAt?: Prisma.SortOrder
  used?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type ValidationCodeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  type?: Prisma.SortOrder
}

export type ValidationCodeCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ValidationCodeCreateWithoutUserInput, Prisma.ValidationCodeUncheckedCreateWithoutUserInput> | Prisma.ValidationCodeCreateWithoutUserInput[] | Prisma.ValidationCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ValidationCodeCreateOrConnectWithoutUserInput | Prisma.ValidationCodeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ValidationCodeCreateManyUserInputEnvelope
  connect?: Prisma.ValidationCodeWhereUniqueInput | Prisma.ValidationCodeWhereUniqueInput[]
}

export type ValidationCodeUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ValidationCodeCreateWithoutUserInput, Prisma.ValidationCodeUncheckedCreateWithoutUserInput> | Prisma.ValidationCodeCreateWithoutUserInput[] | Prisma.ValidationCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ValidationCodeCreateOrConnectWithoutUserInput | Prisma.ValidationCodeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ValidationCodeCreateManyUserInputEnvelope
  connect?: Prisma.ValidationCodeWhereUniqueInput | Prisma.ValidationCodeWhereUniqueInput[]
}

export type ValidationCodeUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ValidationCodeCreateWithoutUserInput, Prisma.ValidationCodeUncheckedCreateWithoutUserInput> | Prisma.ValidationCodeCreateWithoutUserInput[] | Prisma.ValidationCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ValidationCodeCreateOrConnectWithoutUserInput | Prisma.ValidationCodeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ValidationCodeUpsertWithWhereUniqueWithoutUserInput | Prisma.ValidationCodeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ValidationCodeCreateManyUserInputEnvelope
  set?: Prisma.ValidationCodeWhereUniqueInput | Prisma.ValidationCodeWhereUniqueInput[]
  disconnect?: Prisma.ValidationCodeWhereUniqueInput | Prisma.ValidationCodeWhereUniqueInput[]
  delete?: Prisma.ValidationCodeWhereUniqueInput | Prisma.ValidationCodeWhereUniqueInput[]
  connect?: Prisma.ValidationCodeWhereUniqueInput | Prisma.ValidationCodeWhereUniqueInput[]
  update?: Prisma.ValidationCodeUpdateWithWhereUniqueWithoutUserInput | Prisma.ValidationCodeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ValidationCodeUpdateManyWithWhereWithoutUserInput | Prisma.ValidationCodeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ValidationCodeScalarWhereInput | Prisma.ValidationCodeScalarWhereInput[]
}

export type ValidationCodeUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ValidationCodeCreateWithoutUserInput, Prisma.ValidationCodeUncheckedCreateWithoutUserInput> | Prisma.ValidationCodeCreateWithoutUserInput[] | Prisma.ValidationCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ValidationCodeCreateOrConnectWithoutUserInput | Prisma.ValidationCodeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ValidationCodeUpsertWithWhereUniqueWithoutUserInput | Prisma.ValidationCodeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ValidationCodeCreateManyUserInputEnvelope
  set?: Prisma.ValidationCodeWhereUniqueInput | Prisma.ValidationCodeWhereUniqueInput[]
  disconnect?: Prisma.ValidationCodeWhereUniqueInput | Prisma.ValidationCodeWhereUniqueInput[]
  delete?: Prisma.ValidationCodeWhereUniqueInput | Prisma.ValidationCodeWhereUniqueInput[]
  connect?: Prisma.ValidationCodeWhereUniqueInput | Prisma.ValidationCodeWhereUniqueInput[]
  update?: Prisma.ValidationCodeUpdateWithWhereUniqueWithoutUserInput | Prisma.ValidationCodeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ValidationCodeUpdateManyWithWhereWithoutUserInput | Prisma.ValidationCodeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ValidationCodeScalarWhereInput | Prisma.ValidationCodeScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type ValidationCodeCreateWithoutUserInput = {
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  expiredAt: Date | string
  used?: boolean
  type?: number
}

export type ValidationCodeUncheckedCreateWithoutUserInput = {
  id?: number
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  expiredAt: Date | string
  used?: boolean
  type?: number
}

export type ValidationCodeCreateOrConnectWithoutUserInput = {
  where: Prisma.ValidationCodeWhereUniqueInput
  create: Prisma.XOR<Prisma.ValidationCodeCreateWithoutUserInput, Prisma.ValidationCodeUncheckedCreateWithoutUserInput>
}

export type ValidationCodeCreateManyUserInputEnvelope = {
  data: Prisma.ValidationCodeCreateManyUserInput | Prisma.ValidationCodeCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ValidationCodeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ValidationCodeWhereUniqueInput
  update: Prisma.XOR<Prisma.ValidationCodeUpdateWithoutUserInput, Prisma.ValidationCodeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ValidationCodeCreateWithoutUserInput, Prisma.ValidationCodeUncheckedCreateWithoutUserInput>
}

export type ValidationCodeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ValidationCodeWhereUniqueInput
  data: Prisma.XOR<Prisma.ValidationCodeUpdateWithoutUserInput, Prisma.ValidationCodeUncheckedUpdateWithoutUserInput>
}

export type ValidationCodeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ValidationCodeScalarWhereInput
  data: Prisma.XOR<Prisma.ValidationCodeUpdateManyMutationInput, Prisma.ValidationCodeUncheckedUpdateManyWithoutUserInput>
}

export type ValidationCodeScalarWhereInput = {
  AND?: Prisma.ValidationCodeScalarWhereInput | Prisma.ValidationCodeScalarWhereInput[]
  OR?: Prisma.ValidationCodeScalarWhereInput[]
  NOT?: Prisma.ValidationCodeScalarWhereInput | Prisma.ValidationCodeScalarWhereInput[]
  id?: Prisma.IntFilter<"ValidationCode"> | number
  userId?: Prisma.IntFilter<"ValidationCode"> | number
  code?: Prisma.StringFilter<"ValidationCode"> | string
  createdAt?: Prisma.DateTimeFilter<"ValidationCode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ValidationCode"> | Date | string
  expiredAt?: Prisma.DateTimeFilter<"ValidationCode"> | Date | string
  used?: Prisma.BoolFilter<"ValidationCode"> | boolean
  type?: Prisma.IntFilter<"ValidationCode"> | number
}

export type ValidationCodeCreateManyUserInput = {
  id?: number
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  expiredAt: Date | string
  used?: boolean
  type?: number
}

export type ValidationCodeUpdateWithoutUserInput = {
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ValidationCodeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ValidationCodeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  used?: Prisma.BoolFieldUpdateOperationsInput | boolean
  type?: Prisma.IntFieldUpdateOperationsInput | number
}



export type ValidationCodeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  code?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiredAt?: boolean
  used?: boolean
  type?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["validationCode"]>



export type ValidationCodeSelectScalar = {
  id?: boolean
  userId?: boolean
  code?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiredAt?: boolean
  used?: boolean
  type?: boolean
}

export type ValidationCodeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "code" | "createdAt" | "updatedAt" | "expiredAt" | "used" | "type", ExtArgs["result"]["validationCode"]>
export type ValidationCodeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ValidationCodePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ValidationCode"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    code: string
    createdAt: Date
    updatedAt: Date
    expiredAt: Date
    used: boolean
    type: number
  }, ExtArgs["result"]["validationCode"]>
  composites: {}
}

export type ValidationCodeGetPayload<S extends boolean | null | undefined | ValidationCodeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ValidationCodePayload, S>

export type ValidationCodeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ValidationCodeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ValidationCodeCountAggregateInputType | true
  }

export interface ValidationCodeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ValidationCode'], meta: { name: 'ValidationCode' } }
  /**
   * Find zero or one ValidationCode that matches the filter.
   * @param {ValidationCodeFindUniqueArgs} args - Arguments to find a ValidationCode
   * @example
   * // Get one ValidationCode
   * const validationCode = await prisma.validationCode.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ValidationCodeFindUniqueArgs>(args: Prisma.SelectSubset<T, ValidationCodeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ValidationCodeClient<runtime.Types.Result.GetResult<Prisma.$ValidationCodePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ValidationCode that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ValidationCodeFindUniqueOrThrowArgs} args - Arguments to find a ValidationCode
   * @example
   * // Get one ValidationCode
   * const validationCode = await prisma.validationCode.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ValidationCodeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ValidationCodeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ValidationCodeClient<runtime.Types.Result.GetResult<Prisma.$ValidationCodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ValidationCode that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationCodeFindFirstArgs} args - Arguments to find a ValidationCode
   * @example
   * // Get one ValidationCode
   * const validationCode = await prisma.validationCode.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ValidationCodeFindFirstArgs>(args?: Prisma.SelectSubset<T, ValidationCodeFindFirstArgs<ExtArgs>>): Prisma.Prisma__ValidationCodeClient<runtime.Types.Result.GetResult<Prisma.$ValidationCodePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ValidationCode that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationCodeFindFirstOrThrowArgs} args - Arguments to find a ValidationCode
   * @example
   * // Get one ValidationCode
   * const validationCode = await prisma.validationCode.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ValidationCodeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ValidationCodeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ValidationCodeClient<runtime.Types.Result.GetResult<Prisma.$ValidationCodePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ValidationCodes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationCodeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ValidationCodes
   * const validationCodes = await prisma.validationCode.findMany()
   * 
   * // Get first 10 ValidationCodes
   * const validationCodes = await prisma.validationCode.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const validationCodeWithIdOnly = await prisma.validationCode.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ValidationCodeFindManyArgs>(args?: Prisma.SelectSubset<T, ValidationCodeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ValidationCodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ValidationCode.
   * @param {ValidationCodeCreateArgs} args - Arguments to create a ValidationCode.
   * @example
   * // Create one ValidationCode
   * const ValidationCode = await prisma.validationCode.create({
   *   data: {
   *     // ... data to create a ValidationCode
   *   }
   * })
   * 
   */
  create<T extends ValidationCodeCreateArgs>(args: Prisma.SelectSubset<T, ValidationCodeCreateArgs<ExtArgs>>): Prisma.Prisma__ValidationCodeClient<runtime.Types.Result.GetResult<Prisma.$ValidationCodePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ValidationCodes.
   * @param {ValidationCodeCreateManyArgs} args - Arguments to create many ValidationCodes.
   * @example
   * // Create many ValidationCodes
   * const validationCode = await prisma.validationCode.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ValidationCodeCreateManyArgs>(args?: Prisma.SelectSubset<T, ValidationCodeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ValidationCode.
   * @param {ValidationCodeDeleteArgs} args - Arguments to delete one ValidationCode.
   * @example
   * // Delete one ValidationCode
   * const ValidationCode = await prisma.validationCode.delete({
   *   where: {
   *     // ... filter to delete one ValidationCode
   *   }
   * })
   * 
   */
  delete<T extends ValidationCodeDeleteArgs>(args: Prisma.SelectSubset<T, ValidationCodeDeleteArgs<ExtArgs>>): Prisma.Prisma__ValidationCodeClient<runtime.Types.Result.GetResult<Prisma.$ValidationCodePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ValidationCode.
   * @param {ValidationCodeUpdateArgs} args - Arguments to update one ValidationCode.
   * @example
   * // Update one ValidationCode
   * const validationCode = await prisma.validationCode.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ValidationCodeUpdateArgs>(args: Prisma.SelectSubset<T, ValidationCodeUpdateArgs<ExtArgs>>): Prisma.Prisma__ValidationCodeClient<runtime.Types.Result.GetResult<Prisma.$ValidationCodePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ValidationCodes.
   * @param {ValidationCodeDeleteManyArgs} args - Arguments to filter ValidationCodes to delete.
   * @example
   * // Delete a few ValidationCodes
   * const { count } = await prisma.validationCode.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ValidationCodeDeleteManyArgs>(args?: Prisma.SelectSubset<T, ValidationCodeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ValidationCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationCodeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ValidationCodes
   * const validationCode = await prisma.validationCode.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ValidationCodeUpdateManyArgs>(args: Prisma.SelectSubset<T, ValidationCodeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ValidationCode.
   * @param {ValidationCodeUpsertArgs} args - Arguments to update or create a ValidationCode.
   * @example
   * // Update or create a ValidationCode
   * const validationCode = await prisma.validationCode.upsert({
   *   create: {
   *     // ... data to create a ValidationCode
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ValidationCode we want to update
   *   }
   * })
   */
  upsert<T extends ValidationCodeUpsertArgs>(args: Prisma.SelectSubset<T, ValidationCodeUpsertArgs<ExtArgs>>): Prisma.Prisma__ValidationCodeClient<runtime.Types.Result.GetResult<Prisma.$ValidationCodePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ValidationCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationCodeCountArgs} args - Arguments to filter ValidationCodes to count.
   * @example
   * // Count the number of ValidationCodes
   * const count = await prisma.validationCode.count({
   *   where: {
   *     // ... the filter for the ValidationCodes we want to count
   *   }
   * })
  **/
  count<T extends ValidationCodeCountArgs>(
    args?: Prisma.Subset<T, ValidationCodeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ValidationCodeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ValidationCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationCodeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ValidationCodeAggregateArgs>(args: Prisma.Subset<T, ValidationCodeAggregateArgs>): Prisma.PrismaPromise<GetValidationCodeAggregateType<T>>

  /**
   * Group by ValidationCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ValidationCodeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ValidationCodeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ValidationCodeGroupByArgs['orderBy'] }
      : { orderBy?: ValidationCodeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ValidationCodeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetValidationCodeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ValidationCode model
 */
readonly fields: ValidationCodeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ValidationCode.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ValidationCodeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ValidationCode model
 */
export interface ValidationCodeFieldRefs {
  readonly id: Prisma.FieldRef<"ValidationCode", 'Int'>
  readonly userId: Prisma.FieldRef<"ValidationCode", 'Int'>
  readonly code: Prisma.FieldRef<"ValidationCode", 'String'>
  readonly createdAt: Prisma.FieldRef<"ValidationCode", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ValidationCode", 'DateTime'>
  readonly expiredAt: Prisma.FieldRef<"ValidationCode", 'DateTime'>
  readonly used: Prisma.FieldRef<"ValidationCode", 'Boolean'>
  readonly type: Prisma.FieldRef<"ValidationCode", 'Int'>
}
    

// Custom InputTypes
/**
 * ValidationCode findUnique
 */
export type ValidationCodeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationCode
   */
  select?: Prisma.ValidationCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationCode
   */
  omit?: Prisma.ValidationCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationCodeInclude<ExtArgs> | null
  /**
   * Filter, which ValidationCode to fetch.
   */
  where: Prisma.ValidationCodeWhereUniqueInput
}

/**
 * ValidationCode findUniqueOrThrow
 */
export type ValidationCodeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationCode
   */
  select?: Prisma.ValidationCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationCode
   */
  omit?: Prisma.ValidationCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationCodeInclude<ExtArgs> | null
  /**
   * Filter, which ValidationCode to fetch.
   */
  where: Prisma.ValidationCodeWhereUniqueInput
}

/**
 * ValidationCode findFirst
 */
export type ValidationCodeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationCode
   */
  select?: Prisma.ValidationCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationCode
   */
  omit?: Prisma.ValidationCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationCodeInclude<ExtArgs> | null
  /**
   * Filter, which ValidationCode to fetch.
   */
  where?: Prisma.ValidationCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationCodes to fetch.
   */
  orderBy?: Prisma.ValidationCodeOrderByWithRelationInput | Prisma.ValidationCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ValidationCodes.
   */
  cursor?: Prisma.ValidationCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ValidationCodes.
   */
  distinct?: Prisma.ValidationCodeScalarFieldEnum | Prisma.ValidationCodeScalarFieldEnum[]
}

/**
 * ValidationCode findFirstOrThrow
 */
export type ValidationCodeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationCode
   */
  select?: Prisma.ValidationCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationCode
   */
  omit?: Prisma.ValidationCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationCodeInclude<ExtArgs> | null
  /**
   * Filter, which ValidationCode to fetch.
   */
  where?: Prisma.ValidationCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationCodes to fetch.
   */
  orderBy?: Prisma.ValidationCodeOrderByWithRelationInput | Prisma.ValidationCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ValidationCodes.
   */
  cursor?: Prisma.ValidationCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ValidationCodes.
   */
  distinct?: Prisma.ValidationCodeScalarFieldEnum | Prisma.ValidationCodeScalarFieldEnum[]
}

/**
 * ValidationCode findMany
 */
export type ValidationCodeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationCode
   */
  select?: Prisma.ValidationCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationCode
   */
  omit?: Prisma.ValidationCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationCodeInclude<ExtArgs> | null
  /**
   * Filter, which ValidationCodes to fetch.
   */
  where?: Prisma.ValidationCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ValidationCodes to fetch.
   */
  orderBy?: Prisma.ValidationCodeOrderByWithRelationInput | Prisma.ValidationCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ValidationCodes.
   */
  cursor?: Prisma.ValidationCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ValidationCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ValidationCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ValidationCodes.
   */
  distinct?: Prisma.ValidationCodeScalarFieldEnum | Prisma.ValidationCodeScalarFieldEnum[]
}

/**
 * ValidationCode create
 */
export type ValidationCodeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationCode
   */
  select?: Prisma.ValidationCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationCode
   */
  omit?: Prisma.ValidationCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationCodeInclude<ExtArgs> | null
  /**
   * The data needed to create a ValidationCode.
   */
  data: Prisma.XOR<Prisma.ValidationCodeCreateInput, Prisma.ValidationCodeUncheckedCreateInput>
}

/**
 * ValidationCode createMany
 */
export type ValidationCodeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ValidationCodes.
   */
  data: Prisma.ValidationCodeCreateManyInput | Prisma.ValidationCodeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ValidationCode update
 */
export type ValidationCodeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationCode
   */
  select?: Prisma.ValidationCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationCode
   */
  omit?: Prisma.ValidationCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationCodeInclude<ExtArgs> | null
  /**
   * The data needed to update a ValidationCode.
   */
  data: Prisma.XOR<Prisma.ValidationCodeUpdateInput, Prisma.ValidationCodeUncheckedUpdateInput>
  /**
   * Choose, which ValidationCode to update.
   */
  where: Prisma.ValidationCodeWhereUniqueInput
}

/**
 * ValidationCode updateMany
 */
export type ValidationCodeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ValidationCodes.
   */
  data: Prisma.XOR<Prisma.ValidationCodeUpdateManyMutationInput, Prisma.ValidationCodeUncheckedUpdateManyInput>
  /**
   * Filter which ValidationCodes to update
   */
  where?: Prisma.ValidationCodeWhereInput
  /**
   * Limit how many ValidationCodes to update.
   */
  limit?: number
}

/**
 * ValidationCode upsert
 */
export type ValidationCodeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationCode
   */
  select?: Prisma.ValidationCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationCode
   */
  omit?: Prisma.ValidationCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationCodeInclude<ExtArgs> | null
  /**
   * The filter to search for the ValidationCode to update in case it exists.
   */
  where: Prisma.ValidationCodeWhereUniqueInput
  /**
   * In case the ValidationCode found by the `where` argument doesn't exist, create a new ValidationCode with this data.
   */
  create: Prisma.XOR<Prisma.ValidationCodeCreateInput, Prisma.ValidationCodeUncheckedCreateInput>
  /**
   * In case the ValidationCode was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ValidationCodeUpdateInput, Prisma.ValidationCodeUncheckedUpdateInput>
}

/**
 * ValidationCode delete
 */
export type ValidationCodeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationCode
   */
  select?: Prisma.ValidationCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationCode
   */
  omit?: Prisma.ValidationCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationCodeInclude<ExtArgs> | null
  /**
   * Filter which ValidationCode to delete.
   */
  where: Prisma.ValidationCodeWhereUniqueInput
}

/**
 * ValidationCode deleteMany
 */
export type ValidationCodeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ValidationCodes to delete
   */
  where?: Prisma.ValidationCodeWhereInput
  /**
   * Limit how many ValidationCodes to delete.
   */
  limit?: number
}

/**
 * ValidationCode without action
 */
export type ValidationCodeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ValidationCode
   */
  select?: Prisma.ValidationCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ValidationCode
   */
  omit?: Prisma.ValidationCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ValidationCodeInclude<ExtArgs> | null
}
